HEADERS = {
    "User-Agent": "",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate",
    "Referer": "https://hape.diesel.com/",
    "Origin": "https://hape.diesel.com",
    "Connection": "keep-alive",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "no-cors",
    "Sec-Fetch-Site": "same-site",
    "Content-Type": None,
    "Pragma": "no-cache",
    "Cache-Control": "no-cache",
}
